name: 🚨 Emergency Server Fix

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Выберите действие'
        required: true
        default: 'kill-port'
        type: choice
        options:
          - kill-port
          - full-restart
          - force-fix

jobs:
  emergency-fix:
    runs-on: ubuntu-latest
    steps:
    - name: 🚨 Emergency Fix - ${{ github.event.inputs.action }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        timeout: 180s
        script: |
          cd /home/beautyapp/beauty-booking
          
          if [ "${{ github.event.inputs.action }}" = "kill-port" ]; then
            echo "🔫 Освобождаем порт 3000..."
            chmod +x scripts/kill-port-3000.sh
            ./scripts/kill-port-3000.sh
            
          elif [ "${{ github.event.inputs.action }}" = "full-restart" ]; then
            echo "🔄 Полный перезапуск..."
            chmod +x scripts/kill-port-3000.sh
            ./scripts/kill-port-3000.sh
            sleep 3
            sudo -u beautyapp nohup npm start > nohup.out 2>&1 &
            sleep 5
            curl -s http://localhost:3000/api/status || echo "Сервис не отвечает"
            
          elif [ "${{ github.event.inputs.action }}" = "force-fix" ]; then
            echo "🔥 Принудительное исправление..."
            chmod +x scripts/force-fix.sh
            ./scripts/force-fix.sh
          fi
          
          echo "✅ Действие '${{ github.event.inputs.action }}' завершено"